
* An observation on other team's rear endplates.

From what I've observed, the rear endplates have varied shapes. I can't observe any angle when it comes to change in angle from top view.
I'd imagine that having an angled endplate would help turn the car AND would shift the center of pressure backwards while turning. This should make the car a little more manageable in the future.

I wonder how different shapes create different vortices. Obviously this region must have a fine mesh when we use Docker to test our design.
To future V, I wish you Godspeed on your endeavors.

* Angled towards the main plane.

I've designed the endplate to be angled towards the fow of the car. This might seem like an odd thing to do, especially since I haven't heard of an F1 car that's done this.
But I'm rather curious about how angled endplates behave when the car is going around a curve - I'd imagine that the endplates behave like airfoils to an extent and actually push the car towards that direction.
Of course, any force created will be miniscule compared to the car's momentum but I'd like to see how it alters the center of pressure.

* Seperate planes and the boundary surface joining them

This may seem like an unnecessary burden on the manufacturing side, but having a 3d shape that funnels air through the area between the endplate is an interesting idea.
It might actually improve flow seperation after the rear wing, god knows we need help with that.
The slight angle improves this effect a little bit - kinda like the rake angle for the undertray on actual F1 cars. 

* Profile

I haven't seen a pattern for endplates other than it be as large as possible to improve the aspect ratio of the rear wing. And it's rectangular (although I'm assuming that's because the area allowed for rear aerodynamic devices is rectangular.)
I've added a lot of curves to that to check on how vortices form depending on the shape and sharp edges of the endplate. This might seem unnecessary if the vortices formed are beneficial and are caused by sharp edges. As you can imagine, this particular profile is subject to a lot of change and scrutiny in the future.

The profile is rectangular in shape and is modified by four sketches at each corner. The upper left and lower right corners are convex while the upper right and lower left are concave.
The convexity and concavity of the corners has been partially influenced by actual F1 cars - I haven't see any FSAE cars use anything other than a concave upper right corner.

In order to modify the profile, modify the sketches that make up the corners. The basic sketch in each corner defines the lengths of the corner - how big of an area the corner is. The curves sketch defines the radii of the various circles and ellipses that smooten the surface.
The master sketch is based on the other two sketches - I would not change this sketch. It serves as a visual aid for the designer and as a reference for other sketches.




