

* Created 3d molds for fiberglass.
So I know that the traditional method for creating fiberglass moulds is by taking a big ass CNC machine and creating a mold out out wood or metal.
But for our little project, CNC takes too long and we don't need permanent molds.

What we should be doing is making 3D-printed molds out of ABS plastic, lay up fiberglass on that and then peek away the ABS plastic.

Benefits:


Cons:
None I can think of, save for rough surface of an unprocessed mold. I'd reckon that an acetone bath will take care of that. If there's still need for a smooth surface, the use of a coating over the epoxy surface should take are of that.


Problems


* Including surface effects in your CFD

* Installing OpenFoam on Mac OS.
* Get rid of Bootcamp and use virtual box instead. Fuck the whole shutting down bullshit.

Seriously. Fuck that shit.

* Petition for an amazing multicore computer.
Because I need the computing power. Perhaps we can use university clusters? We could even say that the cluster can be used by other departments.

* Strengthening 3d printed parts by injecting with epoxy/fiberglass.


* How turblulators can help with the rear wing.
Preventing flow seperation while having greater angle of attack seems to be a decent idea.

* Different Surface finishes for differnt parts of the car.
First find out how they affect the performance.
Then check how the stuff you have and how you could use that a litle better.

* Creating dimples via 3d printing
So. Much. Easier.
Also, I kinda want to see three things
1) How precise the dimesnions will come out with multiple sides.
2) How 


